rm -rf istantanei/*epot*
rm -rf istantanei/*ekin*
rm -rf istantanei/*etot*
rm -rf istantanei/*temp*
rm -rf istantanei/*press*
rm -rf frames/*.xyz
rm -rf blocchi/*.out
rm -rf progressivi/*.out
rm -rf progressivi/*.100
